#!/bin/bash

echo "🚀 Creating Whop App"
echo "==================="
echo ""

echo "📋 Step 1: Get Your Vercel URL"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Find your 'fitness-crm' project"
echo "3. Copy the production URL (e.g., https://fitness-crm-vercel.vercel.app)"
echo ""

echo "📋 Step 2: Create App with Whop CLI"
echo "Run this command (replace YOUR-VERCEL-URL with your actual URL):"
echo ""
echo "whop apps create \\"
echo "  --name 'Fitness CRM' \\"
echo "  --description 'A comprehensive fitness CRM application for trainers to manage clients, track workouts, and monitor progress' \\"
echo "  --app-url https://YOUR-VERCEL-URL.vercel.app \\"
echo "  --category fitness \\"
echo "  --pricing free"
echo ""

echo "📋 Step 3: Alternative - Create via Dashboard"
echo "1. Go to https://whop.com/dashboard"
echo "2. Click 'Create App' or 'New App'"
echo "3. Fill in:"
echo "   - Name: Fitness CRM"
echo "   - Description: A comprehensive fitness CRM application for trainers to manage clients, track workouts, and monitor progress"
echo "   - App URL: https://YOUR-VERCEL-URL.vercel.app"
echo "   - Category: Fitness"
echo "   - Pricing: Free"
echo "4. Save and publish"
echo ""

echo "📋 Step 4: Get New App ID"
echo "After creating the app:"
echo "1. Copy the new app ID from Whop dashboard"
echo "2. It will look like: app_XXXXXXXXX"
echo "3. Let me know the new app ID and I'll update all the files"
echo ""

echo "📋 Step 5: Update Files"
echo "Once you have the new app ID, I'll update:"
echo "- whop-manifest.json"
echo "- check-whop-app.sh"
echo "- WHOP_TROUBLESHOOTING.md"
echo "- All other references"
echo ""

echo "🎯 The 404 error means the app doesn't exist yet - we need to create it first!"
